apiVersion: apps/v1
kind: Deployment
metadata:
  name: petcare-deployment-ui
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: petcare-ui
  template:
    metadata:
      labels:
        app: petcare-ui
    spec:
      containers:
      - name: petcare-container
        image: zetnguyen17/petcare-frontend:1.0.0-10
        ports:
        - containerPort: 3000